"""
Export request_logs rows generated by the k6 simulator on source_ip
103.129.134.226 that were correctly detected and stored as refresh_abuse,
for model finetuning.

Usage:
    python export_refresh_abuse.py
    python export_refresh_abuse.py --out my_dataset.csv
"""

import argparse
import asyncio
import csv
import os

import asyncpg
from dotenv import load_dotenv

load_dotenv()

SOURCE_IP = "::ffff:103.129.134.226"

QUERY = """
    SELECT * FROM (
        SELECT DISTINCT ON (rl.id)
               rl.id, rl.timestamp, rl.request_id, rl.source_ip, rl.user_agent,
               rl.method, rl.endpoint, rl.status_code, rl.error_code,
               rl.response_time_ms, rl.request_size_bytes, rl.response_size_bytes,
               rl.user_id, rl.is_authenticated, rl.db_query_time_ms, rl.db_error,
               rl.db_error_code, rl.ingested_at, ae.anomaly_type
        FROM request_logs rl
        JOIN anomaly_events ae
             ON rl.id = ANY(ae.related_log_ids)
        WHERE rl.user_agent LIKE '%k6%'
          AND rl.source_ip = $1
          AND ae.anomaly_type = 'refresh_abuse'
        ORDER BY rl.id
    ) sub
    ORDER BY sub.timestamp
"""


async def main(out_path):
    conn = await asyncpg.connect(
        host=os.getenv("DB_HOST"),
        port=int(os.getenv("DB_PORT")),
        database=os.getenv("DB_NAME"),
        user=os.getenv("DB_USER"),
        password=os.getenv("DB_PASSWORD"),
    )
    rows = await conn.fetch(QUERY, SOURCE_IP)
    await conn.close()

    if not rows:
        print("No refresh_abuse rows found.")
        return

    with open(out_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(rows[0].keys())
        for row in rows:
            writer.writerow(row.values())

    print(f"Wrote {len(rows)} refresh_abuse rows to {out_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default="refresh_abuse.csv")
    args = parser.parse_args()

    asyncio.run(main(args.out))
