"""
Export request_logs rows generated by the Hydra brute-force simulator
(identified by user_agent, not by the stored anomaly_type — anomaly_type is
stored per detection window, not per log row, and windows can mix traffic
from two different attack tools) to a CSV file, labeled brute_force, for
model finetuning.

Usage:
    python export_anomaly_logs.py
    python export_anomaly_logs.py --out my_dataset.csv
"""

import argparse
import asyncio
import csv
import os

import asyncpg
from dotenv import load_dotenv

load_dotenv()

QUERY = """
    SELECT rl.id, rl.timestamp, rl.request_id, rl.source_ip, rl.user_agent,
           rl.method, rl.endpoint, rl.status_code, rl.error_code,
           rl.response_time_ms, rl.request_size_bytes, rl.response_size_bytes,
           rl.user_id, rl.is_authenticated, rl.db_query_time_ms, rl.db_error,
           rl.db_error_code, rl.ingested_at, ae.anomaly_type
    FROM request_logs rl
    JOIN anomaly_events ae
         ON rl.id = ANY(ae.related_log_ids)
    WHERE rl.user_agent LIKE '%Hydra%'
    ORDER BY rl.timestamp
"""


async def main(out_path):
    conn = await asyncpg.connect(
        host=os.getenv("DB_HOST"),
        port=int(os.getenv("DB_PORT")),
        database=os.getenv("DB_NAME"),
        user=os.getenv("DB_USER"),
        password=os.getenv("DB_PASSWORD"),
    )
    rows = await conn.fetch(QUERY)
    await conn.close()

    if not rows:
        print("No Hydra rows found.")
        return

    with open(out_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(rows[0].keys())
        for row in rows:
            record = dict(row)
            record["anomaly_type"] = "brute_force"
            writer.writerow(record.values())

    print(f"Wrote {len(rows)} brute_force rows to {out_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default="anomaly_logs.csv")
    args = parser.parse_args()

    asyncio.run(main(args.out))
