"""
Export request_logs rows generated by Apache Bench (ab) DDoS simulator
that were correctly detected and stored as ddos anomalies, for model finetuning.
Limits export to 5000 logs.

Usage:
    python export_ddos_logs.py
    python export_ddos_logs.py --out my_dataset.csv
    python export_ddos_logs.py --limit 10000
"""

import argparse
import asyncio
import csv
import os

import asyncpg
from dotenv import load_dotenv

load_dotenv()

QUERY = """
    SELECT rl.id, rl.timestamp, rl.request_id, rl.source_ip, rl.user_agent,
           rl.method, rl.endpoint, rl.status_code, rl.error_code,
           rl.response_time_ms, rl.request_size_bytes, rl.response_size_bytes,
           rl.user_id, rl.is_authenticated, rl.db_query_time_ms, rl.db_error,
           rl.db_error_code, rl.ingested_at, ae.anomaly_type
    FROM request_logs rl
    LEFT JOIN anomaly_events ae
         ON rl.id = ANY(ae.related_log_ids)
    WHERE rl.user_agent LIKE '%ApacheBench%'
    ORDER BY rl.timestamp
    LIMIT $1
"""


async def main(out_path, limit):
    conn = await asyncpg.connect(
        host=os.getenv("DB_HOST"),
        port=int(os.getenv("DB_PORT")),
        database=os.getenv("DB_NAME"),
        user=os.getenv("DB_USER"),
        password=os.getenv("DB_PASSWORD"),
    )
    rows = await conn.fetch(QUERY, limit)
    await conn.close()

    if not rows:
        print("No ddos rows found.")
        return

    with open(out_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(rows[0].keys())
        for row in rows:
            writer.writerow(row.values())

    print(f"Wrote {len(rows)} ddos rows to {out_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default="ddos_logs.csv")
    parser.add_argument("--limit", type=int, default=5000)
    args = parser.parse_args()

    asyncio.run(main(args.out, args.limit))
