"""
View the most recent request_logs rows generated by a k6 run, along with
whatever anomaly_type (if any) they ended up tagged with.

Usage:
    python view_k6_logs.py                     # last 15 minutes, any IP
    python view_k6_logs.py --minutes 30
    python view_k6_logs.py --ip ::ffff:103.129.134.226
    python view_k6_logs.py --limit 50
"""

import argparse
import asyncio
import os

import asyncpg
from dotenv import load_dotenv

load_dotenv()

QUERY = """
    SELECT rl.id, rl.timestamp, rl.source_ip, rl.user_agent, rl.method,
           rl.endpoint, rl.status_code, rl.response_time_ms, ae.anomaly_type
    FROM request_logs rl
    LEFT JOIN anomaly_events ae
         ON rl.id = ANY(ae.related_log_ids)
    WHERE rl.user_agent LIKE '%k6%'
      AND rl.timestamp >= NOW() - ($1 || ' minutes')::interval
      AND ($2::text IS NULL OR rl.source_ip = $2)
    ORDER BY rl.timestamp DESC
    LIMIT $3
"""


async def main(minutes, ip, limit):
    conn = await asyncpg.connect(
        host=os.getenv("DB_HOST"),
        port=int(os.getenv("DB_PORT")),
        database=os.getenv("DB_NAME"),
        user=os.getenv("DB_USER"),
        password=os.getenv("DB_PASSWORD"),
    )
    rows = await conn.fetch(QUERY, str(minutes), ip, limit)
    await conn.close()

    if not rows:
        print("No k6 rows found in that window.")
        return

    print(f"\n{'='*100}")
    print(f"  {len(rows)} k6 log(s) in the last {minutes} minute(s)")
    print(f"{'='*100}")
    for r in rows:
        print(f"  id={r['id']:<8} ts={r['timestamp']}  ip={r['source_ip']}  "
              f"{r['method']:<6} {r['endpoint']:<30} status={r['status_code']}  "
              f"resp={r['response_time_ms']}ms  anomaly_type={r['anomaly_type']}")
    print(f"{'='*100}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--minutes", type=int, default=15)
    parser.add_argument("--ip", default=None)
    parser.add_argument("--limit", type=int, default=200)
    args = parser.parse_args()

    asyncio.run(main(args.minutes, args.ip, args.limit))
