require("dotenv").config();
const express = require("express");
const cors = require("cors");
const loggerMiddleware = require("./middleware/logger");
const authRoutes = require("./routes/authRoutes");
const recordRoutes = require("./routes/recordRoutes");
const prescriptionRoutes = require("./routes/prescriptionRoutes");
const appointmentRoutes = require("./routes/appointmentRoutes");
const reportRoutes = require("./routes/reportRoutes");
const anomalyRoutes = require("./routes/anomalyRoutes");
const tableViewerRoutes = require("./routes/tableViewerRoutes");
const app = express();
app.use(cors());
app.use(express.json());
app.use(loggerMiddleware);
app.get("/api/health", (req, res) => res.json({ status: "ok" }));
app.use("/api/auth", authRoutes);
app.use("/api/records", recordRoutes);
app.use("/api/prescriptions", prescriptionRoutes);
app.use("/api/appointments", appointmentRoutes);
app.use("/api/reports", reportRoutes);
app.use("/api/anomalies", anomalyRoutes);
app.use("/api/tables", tableViewerRoutes);

app.get("/", (req, res) => {
  res.json({ status: "ok" });
});
app.use((req, res) => res.status(404).json({ message: "Route not found" }));
const PORT = process.env.PORT || 8000;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
module.exports = app;
